data<-read.csv('data/exdata-data-household_power_consumption/household_power_consumption.txt', sep=";")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data<- subset(data, Date>="2007-02-01")
data<- subset(data, Date<="2007-02-02")
install.packages("lubridate")
library('lubridate')
data$weekDay<- weekdays(data$Date, abbreviate=T)
data$DateTime<-paste(as.character(data$Date), as.character(data$Time))
data$DateTime<-strptime(data$DateTime, "%Y-%m-%d %H:%M:%S")
png(file="Plot2.png", width = 480, height = 480)
plot(data$DateTime, as.numeric(data$Global_active_power),ylab = "Global Active Power(kilowatts)", xlab="" , type="l")
dev.off()