data<-read.csv('data/exdata-data-household_power_consumption/household_power_consumption.txt', sep=";")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data<- subset(data, Date>="2007-02-01")
data<- subset(data, Date<="2007-02-02")
install.packages("lubridate")
library('lubridate')
data$weekDay<- weekdays(data$Date, abbreviate=T)
data$DateTime<-paste(as.character(data$Date), as.character(data$Time))
data$DateTime<-strptime(data$DateTime, "%Y-%m-%d %H:%M:%S")
png(file="Plot3.png", width = 480, height = 480)
plot(sample(data$DateTime,40), sample(c(-3:39),40), type="n",xlab="", ylab="Energy sub metering")
with(subset(data,Sub_metering_1!=100000),lines(DateTime,as.numeric(as.character(Sub_metering_1)), col="black"))
with(subset(data,Sub_metering_2!=100000),lines(DateTime,as.numeric(as.character(Sub_metering_2)), col="red"))
with(subset(data,Sub_metering_3!=100000),lines(DateTime,as.numeric(as.character(Sub_metering_3)), col="blue"))
legend("topright", pch="-", col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()